image: chilio/laravel-dusk-ci:stable

before_script:
  - php -v
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

cache:
  paths:
    - vendor
    - storage

stages:
  - test
  - build
  - deploy

#test:
#  stage: test
#  script:
#    - cp .env.example .env
#    - vendor/bin/phpunit
#  except:
#    - schedules

build:
  stage: build
  script:
    - cp .env.example .env
    - php arty packagist:providers
    - php arty packagist:get --p=p/provider-2016$%hash%.json
  #only:
  #  - schedules

pages:
  stage: deploy
  script:
    - mv storage/app/packagist/public/ public/
  artifacts:
    paths:
      - public
      - storage
  only:
    - schedules
