version: '3'

services:
  app:
    build: ./docker
    command: /usr/bin/supervisord
    env_file:
      - .env.docker
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_DEFAULT_OUTPUT
    volumes:
      - .:/var/www
    restart: always
    links:
      - redis

  cron:
    build: ./docker
    command: cron -f
    env_file:
      - .env.docker
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_DEFAULT_OUTPUT
    volumes:
      - .:/var/www
    restart: always
    links:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - ./docker/storage/redis:/data
    ports:
      - "6379:6379"
    restart: always
