version: '3'

services:
  arty:
    image: chilio/laravel-dusk-ci:stable
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: php arty

  serve:
    image: chilio/laravel-dusk-ci:stable
    command: php arty discord:serve
    volumes:
      - .:/app
    working_dir: /app
    restart: always
